import { Lead } from "./types";

export const users: Lead[] = [
  {
    id: 1,
    firstName: 'Jorge',
    lastName: 'Ruiz',
    email: 'jruiz@example.com',
    linkedIn: 'https://www.linkedin.com/in/jruiz',
    visaInterestList: ['O-1'],
    resume: '',
    additionalInfo: 'I need help',
    created: '02/02/2024, 2:45 PM',
    status: 'Pending',
    country: 'Mexico',
  },
  {
    id: 2,
    firstName: 'Aisha',
    lastName: 'Khan',
    email: 'aisha.khan@example.com',
    linkedIn: 'https://www.linkedin.com/in/aishakhan',
    visaInterestList: ['H-1B', 'EB-2'],
    resume: '',
    additionalInfo: 'Looking for sponsorship',
    created: '02/05/2024, 10:15 AM',
    status: 'Reached Out',
    country: 'Pakistan',
  },
  {
    id: 3,
    firstName: 'Liam',
    lastName: 'O\'Connor',
    email: 'liam.oconnor@example.com',
    linkedIn: 'https://www.linkedin.com/in/liamoconnor',
    visaInterestList: ['O-1', 'EB-1'],
    resume: '',
    additionalInfo: 'Interested in tech sector',
    created: '02/07/2024, 5:30 PM',
    status: 'Pending',
    country: 'Ireland',
  },
  {
    id: 4,
    firstName: 'Chen',
    lastName: 'Wei',
    email: 'chen.wei@example.com',
    linkedIn: 'https://www.linkedin.com/in/chenwei',
    visaInterestList: ['H-1B'],
    resume: '',
    additionalInfo: 'Recent graduate in CS',
    created: '02/09/2024, 8:00 AM',
    status: 'Reached Out',
    country: 'China',
  },
  {
    id: 5,
    firstName: 'Elena',
    lastName: 'Ivanova',
    email: 'elena.ivanova@example.com',
    linkedIn: 'https://www.linkedin.com/in/elenai',
    visaInterestList: ['EB-2'],
    resume: '',
    additionalInfo: 'Software engineer with 5 years experience',
    created: '02/11/2024, 3:20 PM',
    status: 'Reached Out',
    country: 'Russia',
  },
  {
    id: 6,
    firstName: 'Samuel',
    lastName: 'Mensah',
    email: 'samuel.mensah@example.com',
    linkedIn: 'https://www.linkedin.com/in/smensah',
    visaInterestList: ['H-1B', 'L-1'],
    resume: '',
    additionalInfo: 'Currently in Canada on work permit',
    created: '02/14/2024, 12:45 PM',
    status: 'Pending',
    country: 'Ghana',
  },
  {
    id: 7,
    firstName: 'Yuki',
    lastName: 'Takahashi',
    email: 'yuki.takahashi@example.com',
    linkedIn: 'https://www.linkedin.com/in/yuki-takahashi',
    visaInterestList: ['J-1'],
    resume: '',
    additionalInfo: 'Researcher in biotech field',
    created: '02/17/2024, 9:10 AM',
    status: 'Reached Out',
    country: 'Japan',
  },
  {
    id: 8,
    firstName: 'Carlos',
    lastName: 'Fernandez',
    email: 'carlos.fernandez@example.com',
    linkedIn: 'https://www.linkedin.com/in/cfernandez',
    visaInterestList: ['O-1'],
    resume: '',
    additionalInfo: 'Award-winning designer',
    created: '02/19/2024, 4:30 PM',
    status: 'Pending',
    country: 'Spain',
  },
  {
    id: 9,
    firstName: 'Adeleke',
    lastName: 'Ogunleye',
    email: 'adeleke.ogunleye@example.com',
    linkedIn: 'https://www.linkedin.com/in/adelekeo',
    visaInterestList: ['EB-3'],
    resume: '',
    additionalInfo: 'Seeking employment in IT',
    created: '02/21/2024, 7:50 AM',
    status: 'Reached Out',
    country: 'Nigeria',
  },
  {
    id: 10,
    firstName: 'Sofia',
    lastName: 'Martinez',
    email: 'sofia.martinez@example.com',
    linkedIn: 'https://www.linkedin.com/in/sofiamartinez',
    visaInterestList: ['H-1B'],
    resume: '',
    additionalInfo: 'Currently on OPT',
    created: '02/23/2024, 1:20 PM',
    status: 'Pending',
    country: 'Argentina',
  },
  {
    id: 11,
    firstName: 'Ravi',
    lastName: 'Sharma',
    email: 'ravi.sharma@example.com',
    linkedIn: 'https://www.linkedin.com/in/rsharma',
    visaInterestList: ['H-1B', 'EB-2'],
    resume: '',
    additionalInfo: 'Senior software engineer',
    created: '02/25/2024, 10:00 AM',
    status: 'Reached Out',
    country: 'India',
  },
  {
    id: 12,
    firstName: 'Isabella',
    lastName: 'De Luca',
    email: 'isabella.deluca@example.com',
    linkedIn: 'https://www.linkedin.com/in/isabelladl',
    visaInterestList: ['O-1', 'EB-1'],
    resume: '',
    additionalInfo: 'Opera singer and performer',
    created: '02/27/2024, 3:30 PM',
    status: 'Pending',
    country: 'Italy',
  },
  {
    id: 13,
    firstName: 'William',
    lastName: 'Anderson',
    email: 'william.anderson@example.com',
    linkedIn: 'https://www.linkedin.com/in/wanderson',
    visaInterestList: ['EB-2', 'L-1'],
    resume: '',
    additionalInfo: 'Finance professional',
    created: '03/01/2024, 8:45 AM',
    status: 'Reached Out',
    country: 'Canada',
  },
  {
    id: 14,
    firstName: 'Fatima',
    lastName: 'Al-Sayed',
    email: 'fatima.alsayed@example.com',
    linkedIn: 'https://www.linkedin.com/in/fatimaalsayed',
    visaInterestList: ['J-1'],
    resume: '',
    additionalInfo: 'Medical researcher',
    created: '03/03/2024, 6:15 PM',
    status: 'Reached Out',
    country: 'Saudi Arabia',
  },
  {
    id: 15,
    firstName: 'Lucas',
    lastName: 'Mendes',
    email: 'lucas.mendes@example.com',
    linkedIn: 'https://www.linkedin.com/in/lucasmendes',
    visaInterestList: ['H-1B'],
    resume: '',
    additionalInfo: 'AI engineer',
    created: '03/05/2024, 11:30 AM',
    status: 'Pending',
    country: 'Brazil',
  },
];
